spring.application.name=collab-board-api

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/collab_board
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:c2VjdXJlLWNvbGxhYi1ib2FyZC1kZXYtc2VjcmV0LWNoYW5nZS1pbi1wcm9kdWN0aW9u}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
